### ISSUE TITLE
LiveTaskResult State

### ISSUE THREAD

**Issue by viamgr** [HosseinMirzaei47/template#6]
https://github.com/HosseinMirzaei47/template/blob/65035a269c80170db8866d678eccbb1547efe20e/app/src/main/java/com/example/template/core/LiveTaskResult.kt#L70

What is the usage of this?

**Comment by HosseinMirzaei47** [comment]
It is now redundant. We wrote it to test something but forgot to delete it. We'll remove it from LiveTaskResult.kt class.
